//! This client's half of the cross-repo transcript.
//!
//! `federation-v5-transcript.json` beside this file is generated by sync-hub's
//! `src/v5/transcript.rs` from fixed seeds, ids, timestamps and nonces, and is
//! checked into that repo byte-identically. Everything in it is OUTPUT of the
//! hub's `handshake.rs`, `grant.rs`, `key.rs` and `tls.rs` — not a spelling two
//! repos agreed on.
//!
//! Why that distinction is the whole point: forty-six names, constants and byte
//! layouts are duplicated across the two repos, and most of them are pinned on
//! both sides. Two pins that never compare are not a contract. They are two
//! repos each faithfully preserving whatever it started with, which is exactly
//! the drift a pin was meant to catch — a hub renamed into `camelCase` grant
//! fields ships green over there and rejects every grant this client lodges.
//!
//! So the tests below never assert a literal. They run THIS crate's
//! `protocol_v5`, `grant`, `key_id` and `handshake` over the transcript's own
//! inputs and require the output to equal the hub's. A wire change here reddens
//! here; a wire change on the hub reddens the hub, and lands in this file the
//! moment the transcript is regenerated.
//!
//! Both directions are covered for every message: this crate must PRODUCE the
//! hub's exact bytes and ACCEPT them. Producing alone would let a serialiser
//! and deserialiser agree on an encoding the hub does not speak; accepting
//! alone is worse still — serde reads a missing `Option` as `None`, so a
//! renamed `scope` parses fine and silently means "unscoped".
//!
//! To regenerate after a deliberate protocol change, from the sync-hub repo:
//!
//! ```text
//! LL_V5_TRANSCRIPT_CLIENT=<this repo's root> \
//!   cargo test -p sync-hub --lib -- --ignored bless_the_transcript
//! ```
//!
//! which writes both copies or neither.

use crate::b64;
use ed25519_dalek::{Signer, SigningKey};
use serde_json::Value;

use super::grant::{
    DecisionStatement, GrantKind, GrantStatement, RevocationStatement, canonical_bytes, grant_id,
    verify, verify_decision, verify_revocation,
};
use super::key_id::KeyId;
use super::protocol_v5::{
    ClientMsg, GrantWire, HeldIndex, HubMsg, PROTOCOL_VERSION, RevocationWire, VaultState,
    client_auth_message, hub_challenge_message,
};

/// `include_str!` rather than a runtime read: a missing or moved transcript is
/// a compile error, never a test that quietly passes over nothing.
const CHECKED_IN: &str = include_str!("federation-v5-transcript.json");

fn transcript() -> Value {
    serde_json::from_str(CHECKED_IN).expect("the checked-in transcript is valid JSON")
}

fn text<'a>(v: &'a Value, key: &str) -> &'a str {
    v[key].as_str().unwrap_or_else(|| panic!("transcript has no string at `{key}`"))
}

fn num(v: &Value, key: &str) -> i64 {
    v[key].as_i64().unwrap_or_else(|| panic!("transcript has no number at `{key}`"))
}

fn seed(inputs: &Value, key: &str) -> SigningKey {
    let bytes = hex::decode(text(inputs, key)).expect("seeds are hex");
    SigningKey::from_bytes(&bytes.try_into().expect("seeds are 32 bytes"))
}

fn bytes(inputs: &Value, key: &str) -> Vec<u8> {
    hex::decode(text(inputs, key)).expect("byte inputs are hex")
}

/// The full failure hint, appended to every mismatch: a red test here is either
/// a break in this crate or a protocol change the hub already made.
const HINT: &str = "this crate's wire output no longer matches the transcript sync-hub \
     produced. Either this change is a break, or the hub changed the protocol and the \
     transcript was regenerated — in which case change this crate to match, do not edit \
     the transcript by hand";

/// Every wire message, serialised by THIS crate from the transcript's inputs
/// and compared against the bytes the hub emitted for the same values.
///
/// Covers, as bytes rather than as agreed names: `PROTOCOL_VERSION`; the
/// `#[serde(tag, rename_all)]` on both enums and all thirteen tags; the field
/// names and ORDER of `ClientHello`, `ClientAuth`, `UploadIndex`, `PutGrant`,
/// `RevokeGrant`, `PutDecision`, `FetchIndex`, `HubChallenge`, `SyncReady`,
/// `Reject`, `UploadAck`, `GrantAck` and `IndexHeader`; the nested
/// `VaultState`, `HeldIndex`, `GrantWire` and `RevocationWire`; and the
/// explicit `"holds":null`.
#[test]
fn this_client_produces_every_message_in_the_transcript() {
    let t = transcript();
    let inp = &t["inputs"];
    let m = &t["messages"];
    let keys = &t["key_ids"];
    let hs = &t["handshake_signed_bytes"];
    let st = &t["statements"];

    let vault_one = text(inp, "vault_one");
    let vault_two = text(inp, "vault_two");
    let held = || HeldIndex {
        sha256: text(inp, "index_sha256").into(),
        note_count: num(inp, "note_count"),
        uploaded_at: num(inp, "uploaded_at"),
    };
    let b64_of = |group: &Value, name: &str, field: &str| -> String {
        text(&group[name], field).to_string()
    };

    let mut produced: Vec<(&str, String)> = Vec::new();
    let mut emit = |name: &'static str, json: String| produced.push((name, json));

    emit(
        "client_hello",
        serde_json::to_string(&ClientMsg::ClientHello {
            key_id: text(keys, "issuer").into(),
            nonce_c: b64::encode(bytes(inp, "nonce_c_hex")),
            vault_ids: vec![vault_one.into(), vault_two.into()],
            protocol_version: PROTOCOL_VERSION,
            model_id: text(inp, "model_id").into(),
            invite_code: None,
        })
        .unwrap(),
    );
    emit(
        "client_auth",
        serde_json::to_string(&ClientMsg::ClientAuth {
            sig_c: text(hs, "client_auth_signature_b64").into(),
        })
        .unwrap(),
    );
    emit(
        "upload_index",
        serde_json::to_string(&ClientMsg::UploadIndex {
            vault_id: vault_one.into(),
            sha256: text(inp, "index_sha256").into(),
            note_count: num(inp, "note_count"),
            schema_version: text(inp, "schema_version").into(),
            model_id: text(inp, "model_id").into(),
        })
        .unwrap(),
    );
    emit(
        "put_grant",
        serde_json::to_string(&ClientMsg::PutGrant {
            statement_b64: b64_of(st, "grant_follow", "statement_b64"),
            signature_b64: b64_of(st, "grant_follow", "signature_b64"),
        })
        .unwrap(),
    );
    emit(
        "revoke_grant",
        serde_json::to_string(&ClientMsg::RevokeGrant {
            statement_b64: b64_of(st, "revocation_scoped", "statement_b64"),
            signature_b64: b64_of(st, "revocation_scoped", "signature_b64"),
        })
        .unwrap(),
    );
    emit(
        "put_decision",
        serde_json::to_string(&ClientMsg::PutDecision {
            statement_b64: b64_of(st, "decision_accept", "statement_b64"),
            signature_b64: b64_of(st, "decision_accept", "signature_b64"),
        })
        .unwrap(),
    );
    emit(
        "fetch_index",
        serde_json::to_string(&ClientMsg::FetchIndex { vault_id: vault_one.into() }).unwrap(),
    );
    emit(
        "hub_challenge",
        serde_json::to_string(&HubMsg::HubChallenge {
            nonce_h: b64::encode(bytes(inp, "nonce_h_hex")),
            hub_key_id: text(keys, "hub").into(),
            sig_h: text(hs, "hub_challenge_signature_b64").into(),
        })
        .unwrap(),
    );
    emit(
        "sync_ready",
        serde_json::to_string(&HubMsg::SyncReady {
            protocol_version: PROTOCOL_VERSION,
            vault_state: vec![
                VaultState { vault_id: vault_one.into(), holds: None },
                VaultState { vault_id: vault_two.into(), holds: Some(held()) },
            ],
            grants: vec![GrantWire {
                statement_b64: b64_of(st, "grant_follow", "statement_b64"),
                signature_b64: b64_of(st, "grant_follow", "signature_b64"),
                state: "active".into(),
            }],
            revocations: vec![RevocationWire {
                statement_b64: b64_of(st, "revocation_unscoped", "statement_b64"),
                signature_b64: b64_of(st, "revocation_unscoped", "signature_b64"),
            }],
        })
        .unwrap(),
    );
    emit(
        "reject",
        serde_json::to_string(&HubMsg::Reject { reason: text(inp, "reject_reason").into() })
            .unwrap(),
    );
    emit(
        "upload_ack",
        serde_json::to_string(&HubMsg::UploadAck {
            vault_id: vault_one.into(),
            sha256: text(inp, "index_sha256").into(),
        })
        .unwrap(),
    );
    emit(
        "grant_ack",
        serde_json::to_string(&HubMsg::GrantAck {
            grant_id: b64_of(st, "grant_follow", "statement_sha256"),
        })
        .unwrap(),
    );
    emit(
        "index_header_holds",
        serde_json::to_string(&HubMsg::IndexHeader {
            vault_id: vault_two.into(),
            holds: Some(held()),
        })
        .unwrap(),
    );
    emit(
        "index_header_empty",
        serde_json::to_string(&HubMsg::IndexHeader { vault_id: vault_one.into(), holds: None })
            .unwrap(),
    );

    for (name, json) in &produced {
        assert_eq!(json.as_str(), text(m, name), "message `{name}`: {HINT}");
    }

    // Assert the complement is empty rather than listing what is covered: a
    // list of the messages this test happens to build can only ever agree with
    // itself, and the transcript growing a message nobody exercises is the
    // failure mode that matters.
    let mut covered: Vec<&str> = produced.iter().map(|(n, _)| *n).collect();
    covered.sort_unstable();
    let mut present: Vec<&str> =
        m.as_object().expect("messages is an object").keys().map(String::as_str).collect();
    present.sort_unstable();
    assert_eq!(covered, present, "every transcript message must be produced above");
}

/// The other direction: this crate's deserialiser accepts the hub's bytes and
/// recovers the right values. `SyncReady`, `HubChallenge`, `Reject`,
/// `UploadAck`, `GrantAck` and `IndexHeader` are the only messages this client
/// ever reads for real, so a parse test alone can be satisfied by a shape the
/// hub does not emit — which is why the producing test above exists too.
#[test]
fn this_client_accepts_every_message_in_the_transcript() {
    let t = transcript();
    let inp = &t["inputs"];
    let m = &t["messages"];
    let st = &t["statements"];
    let mut seen: Vec<&str> = Vec::new();

    for name in ["client_hello", "client_auth", "upload_index", "put_grant", "revoke_grant",
                 "put_decision", "fetch_index"] {
        seen.push(name);
        serde_json::from_str::<ClientMsg>(text(m, name))
            .unwrap_or_else(|e| panic!("client message `{name}` must parse: {e}"));
    }
    for name in ["hub_challenge", "sync_ready", "reject", "upload_ack", "grant_ack",
                 "index_header_holds", "index_header_empty"] {
        seen.push(name);
        serde_json::from_str::<HubMsg>(text(m, name))
            .unwrap_or_else(|e| panic!("hub message `{name}` must parse: {e}"));
    }

    // Then the values, on the messages whose contents this client acts on.
    match serde_json::from_str::<ClientMsg>(text(m, "client_hello")).unwrap() {
        ClientMsg::ClientHello { key_id, protocol_version, invite_code, .. } => {
            assert_eq!(key_id, text(&t["key_ids"], "issuer"));
            assert_eq!(protocol_version, PROTOCOL_VERSION);
            assert_eq!(invite_code, None, "an absent invite is null, not an empty string");
        }
        other => panic!("wrong variant: {other:?}"),
    }
    match serde_json::from_str::<HubMsg>(text(m, "sync_ready")).unwrap() {
        HubMsg::SyncReady { protocol_version, vault_state, grants, revocations } => {
            assert_eq!(protocol_version, PROTOCOL_VERSION);
            assert!(
                vault_state[0].holds.is_none(),
                "`null` must mean 'the hub holds nothing' — the value that triggers a re-upload"
            );
            let held = vault_state[1].holds.as_ref().expect("vault_two holds an index");
            assert_eq!(held.sha256, text(inp, "index_sha256"));
            assert_eq!(held.note_count, num(inp, "note_count"));
            assert_eq!(held.uploaded_at, num(inp, "uploaded_at"));
            assert_eq!(grants[0].state, "active");
            assert_eq!(grants[0].statement_b64, text(&st["grant_follow"], "statement_b64"));
            assert_eq!(
                revocations[0].statement_b64,
                text(&st["revocation_unscoped"], "statement_b64"),
                "a revocation is a signed statement, not a bare id"
            );
        }
        other => panic!("wrong variant: {other:?}"),
    }
    match serde_json::from_str::<HubMsg>(text(m, "hub_challenge")).unwrap() {
        HubMsg::HubChallenge { nonce_h, hub_key_id, sig_h } => {
            assert_eq!(hub_key_id, text(&t["key_ids"], "hub"));
            assert!(
                KeyId::parse(&hub_key_id).is_ok(),
                "the hub sends a real key_id; a fixture this client would reject is not one"
            );
            assert_eq!(b64::decode(&nonce_h).unwrap().len(), 32);
            assert_eq!(b64::decode(&sig_h).unwrap().len(), 64);
        }
        other => panic!("wrong variant: {other:?}"),
    }
    match serde_json::from_str::<HubMsg>(text(m, "grant_ack")).unwrap() {
        HubMsg::GrantAck { grant_id } => {
            assert_eq!(grant_id, text(&st["grant_follow"], "statement_sha256"));
        }
        other => panic!("wrong variant: {other:?}"),
    }
    match serde_json::from_str::<HubMsg>(text(m, "index_header_empty")).unwrap() {
        HubMsg::IndexHeader { holds, .. } => assert!(holds.is_none()),
        other => panic!("wrong variant: {other:?}"),
    }

    seen.sort_unstable();
    let mut present: Vec<&str> =
        m.as_object().expect("messages is an object").keys().map(String::as_str).collect();
    present.sort_unstable();
    assert_eq!(seen, present, "every transcript message must be parsed above");
}

/// Every signed statement, rebuilt from the transcript's inputs through THIS
/// crate's types and signed with the same seeds. Equality of `statement_json`
/// pins `GrantStatement`'s eight field names and their order, all four
/// `GrantKind` wire values, `DecisionStatement`'s `kind`, and
/// `RevocationStatement`'s `scope`; equality of `signature_b64` proves the
/// bytes are identical down to the last byte, since ed25519 over different
/// messages cannot collide.
///
/// `expires_at` is not carried as an input — it is derived here from
/// `default_ttl_secs`, so the 365-day and 90-day TTLs are part of what this
/// pins rather than a number copied across.
#[test]
fn this_client_produces_every_signed_statement_in_the_transcript() {
    let t = transcript();
    let inp = &t["inputs"];
    let st = &t["statements"];
    let sk_issuer = seed(inp, "seed_issuer_hex");
    let sk_subject = seed(inp, "seed_subject_hex");
    let issuer = KeyId::from_pubkey(&sk_issuer.verifying_key());
    let subject = KeyId::from_pubkey(&sk_subject.verifying_key());
    let issued_at = num(inp, "issued_at");
    let vault_one = text(inp, "vault_one");

    let mut covered: Vec<&str> = Vec::new();
    let mut check = |name: &'static str, sk: &SigningKey, bytes: Vec<u8>| {
        covered.push(name);
        let entry = &st[name];
        let sig = sk.sign(&bytes);
        assert_eq!(
            String::from_utf8(bytes.clone()).unwrap(),
            text(entry, "statement_json"),
            "statement `{name}`: {HINT}"
        );
        assert_eq!(b64::encode(&bytes), text(entry, "statement_b64"), "statement `{name}`");
        assert_eq!(
            b64::encode(sig.to_bytes()),
            text(entry, "signature_b64"),
            "statement `{name}`: same bytes must sign to the same signature"
        );
        assert_eq!(grant_id(&bytes), text(entry, "statement_sha256"), "statement `{name}`");
    };

    let grant = |kind: GrantKind, scope: Option<&str>| {
        canonical_bytes(&GrantStatement {
            v: 5,
            kind,
            from: issuer.clone(),
            to: subject.clone(),
            scope: scope.map(str::to_string),
            issued_at,
            expires_at: issued_at + kind.default_ttl_secs(),
            nonce: text(inp, "grant_nonce").into(),
        })
    };
    check("grant_follow", &sk_issuer, grant(GrantKind::Follow, None));
    check("grant_link", &sk_issuer, grant(GrantKind::Link, None));
    check("grant_assoc", &sk_issuer, grant(GrantKind::Assoc, None));
    check("grant_peer", &sk_issuer, grant(GrantKind::Peer, None));
    check("grant_follow_scoped", &sk_issuer, grant(GrantKind::Follow, Some(vault_one)));

    let decision = |kind: &'static str, on: &str, at: i64| {
        canonical_bytes(&DecisionStatement {
            v: 5,
            kind,
            grant_id: text(&st[on], "statement_sha256").into(),
            by: subject.clone(),
            at,
        })
    };
    check(
        "decision_accept",
        &sk_subject,
        decision("accept", "grant_follow", num(inp, "accept_at")),
    );
    check("decision_deny", &sk_subject, decision("deny", "grant_link", num(inp, "deny_at")));

    let revocation = |on: &str, scope: Option<&str>, at: i64| {
        canonical_bytes(&RevocationStatement {
            v: 5,
            kind: "revoke",
            grant_id: text(&st[on], "statement_sha256").into(),
            by: issuer.clone(),
            scope: scope.map(str::to_string),
            at,
        })
    };
    check(
        "revocation_unscoped",
        &sk_issuer,
        revocation("grant_link", None, num(inp, "revoke_unscoped_at")),
    );
    check(
        "revocation_scoped",
        &sk_issuer,
        revocation("grant_follow_scoped", Some(vault_one), num(inp, "revoke_scoped_at")),
    );

    covered.sort_unstable();
    let mut present: Vec<&str> =
        st.as_object().expect("statements is an object").keys().map(String::as_str).collect();
    present.sort_unstable();
    assert_eq!(covered, present, "every transcript statement must be produced above");
}

/// And this crate's `verify*` accepts the hub's bytes and signatures.
///
/// This is the direction a round-trip cannot reach. Renaming
/// `RevocationStatement::scope` on the serialising side leaves a round-trip
/// green — serde reads the now-missing `Option` as `None`, so the statement
/// still parses and silently means "every vault this issuer owns". Here the
/// scope is asserted against the value the hub signed.
#[test]
fn this_client_verifies_every_signed_statement_in_the_transcript() {
    let t = transcript();
    let inp = &t["inputs"];
    let st = &t["statements"];
    let issuer = KeyId::parse(text(&t["key_ids"], "issuer")).unwrap();
    let subject = KeyId::parse(text(&t["key_ids"], "subject")).unwrap();
    let vault_one = text(inp, "vault_one");
    let issued_at = num(inp, "issued_at");

    let raw = |name: &str| b64::decode(text(&st[name], "statement_b64")).unwrap();
    let sig = |name: &str| b64::decode(text(&st[name], "signature_b64")).unwrap();

    for (name, kind, scope) in [
        ("grant_follow", GrantKind::Follow, None),
        ("grant_link", GrantKind::Link, None),
        ("grant_assoc", GrantKind::Assoc, None),
        ("grant_peer", GrantKind::Peer, None),
        ("grant_follow_scoped", GrantKind::Follow, Some(vault_one)),
    ] {
        let g = verify(&raw(name), &sig(name), &issuer)
            .unwrap_or_else(|e| panic!("grant `{name}` must verify: {e}"));
        assert_eq!(g.kind, kind, "{name}");
        assert_eq!(g.to, subject, "{name}");
        assert_eq!(g.scope.as_deref(), scope, "{name}");
        assert_eq!(g.issued_at, issued_at, "{name}");
        assert_eq!(g.expires_at, issued_at + kind.default_ttl_secs(), "{name}");
    }

    for (name, kind, on) in [
        ("decision_accept", "accept", "grant_follow"),
        ("decision_deny", "deny", "grant_link"),
    ] {
        let d = verify_decision(&raw(name), &sig(name), &subject)
            .unwrap_or_else(|e| panic!("decision `{name}` must verify: {e}"));
        assert_eq!(d.kind, kind, "{name}");
        assert_eq!(d.v, 5, "{name}");
        assert_eq!(d.grant_id, text(&st[on], "statement_sha256"), "{name}");
    }

    for (name, scope, on) in [
        ("revocation_unscoped", None, "grant_link"),
        ("revocation_scoped", Some(vault_one), "grant_follow_scoped"),
    ] {
        let r = verify_revocation(&raw(name), &sig(name), &issuer)
            .unwrap_or_else(|e| panic!("revocation `{name}` must verify: {e}"));
        assert_eq!(r.kind, "revoke", "{name}");
        assert_eq!(r.scope.as_deref(), scope, "{name}");
        assert_eq!(r.grant_id, text(&st[on], "statement_sha256"), "{name}");
    }
}

/// The two signed handshake byte layouts, produced by this crate's `framed`,
/// against the hub's hex — and then the hub's real signatures verified over
/// this crate's bytes.
///
/// The hex pins the domain prefix, the 4-byte BIG-endian length prefix and the
/// field order in one value. Every other test on these two functions in this
/// crate is an `assert_ne!` between two outputs of the SAME function, which is
/// true under any encoding both calls share: that is how `to_be_bytes` ->
/// `to_le_bytes`, extended domain prefixes and a swapped nonce order were all
/// green on one side. The signature checks are the stronger half — a signature
/// the hub made over the hub's framing verifies against bytes this crate built,
/// which is exactly the property a live handshake needs and no equality of
/// spellings can supply.
#[test]
fn this_client_reproduces_the_transcripts_handshake_bytes() {
    let t = transcript();
    let inp = &t["inputs"];
    let hs = &t["handshake_signed_bytes"];
    let hub = KeyId::parse(text(&t["key_ids"], "hub")).unwrap();
    let issuer = KeyId::parse(text(&t["key_ids"], "issuer")).unwrap();

    let nonce_h = bytes(inp, "nonce_h_hex");
    let nonce_c = bytes(inp, "nonce_c_hex");
    let exporter = bytes(inp, "exporter_hex");

    let hub_bytes = hub_challenge_message(&nonce_h, &nonce_c, &exporter);
    let client_bytes = client_auth_message(&nonce_h, &nonce_c, hub.as_str(), &exporter);
    assert_eq!(hex::encode(&hub_bytes), text(hs, "hub_challenge_message_hex"), "{HINT}");
    assert_eq!(hex::encode(&client_bytes), text(hs, "client_auth_message_hex"), "{HINT}");

    hub.verify(&hub_bytes, &b64::decode(text(hs, "hub_challenge_signature_b64")).unwrap())
        .expect("the hub's own sig_h must verify over the bytes this client builds");
    issuer
        .verify(&client_bytes, &b64::decode(text(hs, "client_auth_signature_b64")).unwrap())
        .expect("a sig_c the hub accepted must verify over the bytes this client builds");
}

/// Seed to `key_id`, for every key the transcript names: the multicodec prefix,
/// the multibase `z` and the base58 alphabet, pinned together as one value.
#[test]
fn this_client_reproduces_the_transcripts_key_ids() {
    let t = transcript();
    let inp = &t["inputs"];
    for (seed_key, id_key) in [
        ("seed_issuer_hex", "issuer"),
        ("seed_subject_hex", "subject"),
        ("seed_hub_hex", "hub"),
        ("seed_pinned_hex", "pinned_seed_7"),
    ] {
        let sk = seed(inp, seed_key);
        assert_eq!(
            KeyId::from_pubkey(&sk.verifying_key()).as_str(),
            text(&t["key_ids"], id_key),
            "{id_key}: {HINT}"
        );
    }
}

/// The TLS exporter label, from this crate's own constant.
///
/// The other two parameters — the 32-byte length and the `None` context — are
/// arguments at `client.rs`'s `export_keying_material` call, not constants, so
/// nothing here can name them; the hub pins all three against a live TLS
/// connection in `tls::tests::the_exporter_matches_the_transcripts_label_
/// length_and_context`.
#[test]
fn this_client_reproduces_the_transcripts_exporter_label() {
    let t = transcript();
    assert_eq!(
        super::handshake::EXPORTER_LABEL,
        text(&t["tls_exporter"], "label").as_bytes(),
        "the exporter label is half of the channel binding; a mismatch makes every \
         handshake fail with `invalid signature` and nothing else. {HINT}"
    );
}
